ktor:
    application:
        modules:
            - ru.ari.ApplicationKt.module
    deployment:
        port: 8080
db:
  driver: "org.postgresql.Driver"
  jdbcUrl: "jdbc:postgresql://db:5432/tasks"
  user: "postgres"
  password: "postgres"
  maximumPoolSize: 10